// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/transport/grpc/proto/auth.proto

package routeguide

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInCredentials) Reset() {
	*x = SignInCredentials{}
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInCredentials) ProtoMessage() {}

func (x *SignInCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInCredentials.ProtoReflect.Descriptor instead.
func (*SignInCredentials) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SignInCredentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignInCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=firstName,proto3" json:"firstName,omitempty"`
	SecondName    string                 `protobuf:"bytes,6,opt,name=secondName,proto3" json:"secondName,omitempty"`
	Age           int32                  `protobuf:"varint,7,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserData) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserData) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *UserData) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type SignInReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInReply) Reset() {
	*x = SignInReply{}
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInReply) ProtoMessage() {}

func (x *SignInReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInReply.ProtoReflect.Descriptor instead.
func (*SignInReply) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SignInReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type SignUpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpReply) Reset() {
	*x = SignUpReply{}
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpReply) ProtoMessage() {}

func (x *SignUpReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpReply.ProtoReflect.Descriptor instead.
func (*SignUpReply) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SignUpReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_internal_transport_grpc_proto_auth_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_proto_auth_proto_rawDesc = "" +
	"\n" +
	"(internal/transport/grpc/proto/auth.proto\"E\n" +
	"\x11SignInCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xbc\x01\n" +
	"\bUserData\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1c\n" +
	"\tfirstName\x18\x05 \x01(\tR\tfirstName\x12\x1e\n" +
	"\n" +
	"secondName\x18\x06 \x01(\tR\n" +
	"secondName\x12\x10\n" +
	"\x03age\x18\a \x01(\x05R\x03age\")\n" +
	"\vSignInReply\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\")\n" +
	"\vSignUpReply\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2Y\n" +
	"\x04Auth\x12,\n" +
	"\x06SignIn\x12\x12.SignInCredentials\x1a\f.SignInReply\"\x00\x12#\n" +
	"\x06SignUp\x12\t.UserData\x1a\f.SignUpReply\"\x00B8Z6google.golang.org/grpc/examples/route_guide/routeguideb\x06proto3"

var (
	file_internal_transport_grpc_proto_auth_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_auth_proto_rawDescData []byte
)

func file_internal_transport_grpc_proto_auth_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_auth_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_auth_proto_rawDesc), len(file_internal_transport_grpc_proto_auth_proto_rawDesc)))
	})
	return file_internal_transport_grpc_proto_auth_proto_rawDescData
}

var file_internal_transport_grpc_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_transport_grpc_proto_auth_proto_goTypes = []any{
	(*SignInCredentials)(nil), // 0: SignInCredentials
	(*UserData)(nil),          // 1: UserData
	(*SignInReply)(nil),       // 2: SignInReply
	(*SignUpReply)(nil),       // 3: SignUpReply
}
var file_internal_transport_grpc_proto_auth_proto_depIdxs = []int32{
	0, // 0: Auth.SignIn:input_type -> SignInCredentials
	1, // 1: Auth.SignUp:input_type -> UserData
	2, // 2: Auth.SignIn:output_type -> SignInReply
	3, // 3: Auth.SignUp:output_type -> SignUpReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_auth_proto_init() }
func file_internal_transport_grpc_proto_auth_proto_init() {
	if File_internal_transport_grpc_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_auth_proto_rawDesc), len(file_internal_transport_grpc_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_auth_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_auth_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_proto_auth_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_auth_proto = out.File
	file_internal_transport_grpc_proto_auth_proto_goTypes = nil
	file_internal_transport_grpc_proto_auth_proto_depIdxs = nil
}
